export const tempAdminData = [
  {
    id: "1",
    name: "Wilson",
    email: "wilson@gmail.com",
    departmentID: "1",
  },
  {
    id: "2",
    name: "XYZ",
    email: "xyz@gmail.com",
    departmentID: "2",
  },
  {
    id: "3",
    name: "surath",
    email: "jhakal.surath@gmail.com",
    departmentID: "1",
  },
  {
    id: "4",
    name: "Modi",
    email: "modi@gmail.com",
    departmentID: "2",
  },
];

export const tempDepartmentData = [
  {
    id: "1",
    name: "IT Department",
  },
  {
    id: "2",
    name: "Commerce Department",
  },
  {
    id: "3",
    name: "Science Department",
  },
];

export const tempCourseData = [
  {
    id: "1",
    name: "Bsc IT",
    departmentID: "1",
  },
  {
    id: "2",
    name: "BVoc",
    departmentID: "1",
  },
  {
    id: "3",
    name: "Bsc Computer Science",
    departmentID: "1",
  },
];

export const tempLectureData = [
  {
    id: "1",
    subjectID: "2",
    time: "2023-08-05T05:53:51.831Z",
    teacherID: "4",
    studentPresentIDs: ["1", "5"],
    studentAbsentIDs: ["6"],
    courseID: "1",
    year: "3",
    departmentID: "1",
  },
  {
    id: "2",
    subjectID: "1",
    time: "2023-08-05T05:53:51.831Z",
    teacherID: "1",
    studentPresentIDs: ["1", "5"],
    studentAbsentIDs: ["6"],
    courseID: "1",
    year: "3",
    departmentID: "1",
  },
];

export const tempSubjectsData = [
  {
    id: "1",
    name: "MAD",
    sem: "5",
    year: "3",
    courseID: "1",
    teacherID: "1",
    departmentID: "1",
  },
  {
    id: "2",
    name: "TOC",
    sem: "5",
    year: "3",
    courseID: "1",
    teacherID: "4",
    departmentID: "1",
  },
  {
    id: "3",
    name: "Python",
    sem: "4",
    year: "2",
    courseID: "1",
    teacherID: "3",
    departmentID: "1",
  },
  {
    id: "4",
    name: "Python",
    sem: "4",
    year: "2",
    courseID: "1",
    teacherID: "3",
    departmentID: "1",
  },
  {
    id: "5",
    name: "Python",
    sem: "4",
    year: "2",
    courseID: "1",
    teacherID: "3",
    departmentID: "1",
  },
];

export const tempStudentsData = [
  {
    id: "1",
    uid: "20BIT022",
    name: "Surath Jhakal",
    email: "jhakal.surath@gmail.com",
    year: "3",
    sem: "5",
    courseID: "1",
    departmentID: "1",
  },
  {
    id: "2",
    uid: "20BIT042",
    name: "Modi",
    email: "modi@gmail.com",
    year: "2",
    sem: "3",
    courseID: "1",
    departmentID: "1",
  },
  {
    id: "3",
    uid: "20BIT043",
    name: "Rahul",
    email: "rahul@gmail.com",
    year: "2",
    sem: "3",
    courseID: "1",
    departmentID: "1",
  },
  {
    id: "4",
    uid: "20BIT044",
    name: "Mamta",
    email: "mamta@gmail.com",
    year: "2",
    sem: "3",
    courseID: "1",
    departmentID: "1",
  },
  {
    id: "5",
    uid: "20BIT020",
    name: "mahima",
    email: "mahima@gmail.com",
    year: "3",
    sem: "5",
    courseID: "1",
    departmentID: "1",
  },
  {
    id: "6",
    uid: "20BIT025",
    name: "Amal",
    email: "Amal@gmail.com",
    year: "3",
    sem: "5",
    courseID: "1",
    departmentID: "1",
  },
  {
    id: "7",
    uid: "21BIT043",
    name: "Dev",
    email: "dev@gmail.com",
    year: "1",
    sem: "2",
    courseID: "1",
    departmentID: "1",
  },
  {
    id: "8",
    uid: "21BIT043",
    name: "Anuj",
    email: "anuj@gmail.com",
    year: "1",
    sem: "2",
    courseID: "1",
    departmentID: "1",
  },
  {
    id: "9",
    uid: "21BIT043",
    name: "Aryan",
    email: "aryan@gmail.com",
    year: "1",
    sem: "2",
    courseID: "2",
    departmentID: "1",
  },
];

export const tempTeacherData = [
  {
    id: "1",
    name: "Sunita",
    email: "sunita@gmail.com",
    adminID: "1",
    courseIDs: ["1", "2"],
    departmentID: "1",
  },
  {
    id: "2",
    name: "Aafreen",
    email: "aafreen@gmail.com",
    adminID: "1",
    courseIDs: ["1"],
    departmentID: "1",
  },
  {
    id: "3",
    name: "Shruti",
    email: "shruti@gmail.com",
    adminID: "3",
    courseIDs: ["1", "2"],
    departmentID: "1",
  },
  {
    id: "4",
    name: "fatima",
    email: "fatima@gmail.com",
    adminID: "3",
    courseIDs: ["2"],
    departmentID: "1",
  },
  {
    id: "5",
    name: "Wilson",
    email: "wilson@gmail.com",
    adminID: "1",
    courseIDs: ["1"],
    departmentID: "1",
  },
  {
    id: "6",
    name: "Preeti",
    email: "preeti@gmail.com",
    adminID: "1",
    courseIDs: ["2"],
    departmentID: "1",
  },
];
